# permissions for end users to edit netbootdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netbootdeployment-editor-role
rules:
- apiGroups:
  - build.kairos.io
  resources:
  - netbootdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - build.kairos.io
  resources:
  - netbootdeployments/status
  verbs:
  - get
