apiVersion: v1
kind: Service
metadata:
    labels:
        control-plane: controller-manager
    name: '{{ include "helm-chart.fullname" . }}-metrics-service'
    namespace: '{{.Release.Namespace}}'
spec:
    ports:
      - name: https
        port: 8443
        protocol: TCP
        targetPort: https
    selector:
        {{- include "helm-chart.selectorLabels" . | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
    name: osartifactbuilder-operator-osbuilder-nginx
    namespace: '{{.Release.Namespace}}'
spec:
    ports:
      - port: 80
        protocol: TCP
        targetPort: 80
    selector:
        app.kubernetes.io/name: osbuilder-nginx
    type: NodePort
